
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  8 2020 21:38:47 +07 (Aug  8 2020 14:38:47 UTC)

// Verification Directory fv/boundflasher 

module boundflasher(led, clk, rst, flick);
  input clk, rst, flick;
  output [15:0] led;
  wire clk, rst, flick;
  wire [15:0] led;
  wire [2:0] state;
  wire [15:0] led_next;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_205, n_206, n_207, n_210;
  CLKBUFX2 cdn_loop_breaker(.A (state[2]), .Y (n_207));
  CLKBUFX2 cdn_loop_breaker80(.A (state[1]), .Y (n_206));
  CLKBUFX2 cdn_loop_breaker81(.A (state[0]), .Y (n_205));
  INVXL g1018(.A (state[2]), .Y (n_93));
  INVXL g1017(.A (state[2]), .Y (n_92));
  OR3X1 g1325__2398(.A (n_85), .B (n_90), .C (n_89), .Y (state[1]));
  OR2X2 g1326__5107(.A (n_91), .B (n_89), .Y (state[0]));
  OR2X2 g1327__6260(.A (n_85), .B (n_88), .Y (state[2]));
  OAI222XL g1328__4319(.A0 (n_205), .A1 (n_80), .B0 (n_206), .B1
       (n_82), .C0 (n_84), .C1 (led[5]), .Y (n_91));
  OAI221X1 g1329__8428(.A0 (n_206), .A1 (n_79), .B0 (n_81), .B1
       (flick), .C0 (n_87), .Y (n_90));
  OAI21XL g1330__5526(.A0 (n_76), .A1 (n_86), .B0 (n_83), .Y (n_88));
  OAI32X1 g1331__6783(.A0 (n_77), .A1 (n_72), .A2 (led[10]), .B0
       (n_76), .B1 (n_74), .Y (n_89));
  NAND2BXL g1332__3680(.AN (n_84), .B (led[5]), .Y (n_87));
  NOR2XL g1334__1617(.A (n_205), .B (n_210), .Y (n_86));
  NOR4BBX1 g1335__2802(.AN (n_207), .BN (led[0]), .C (n_205), .D
       (n_72), .Y (n_85));
  OAI2BB1X1 g1336__1705(.A0N (led[0]), .A1N (n_75), .B0 (flick), .Y
       (n_210));
  OA21X1 g1337__5122(.A0 (n_76), .A1 (n_71), .B0 (n_81), .Y (n_84));
  NAND3BXL g1338__8246(.AN (n_77), .B (n_206), .C (led[10]), .Y (n_83));
  AOI2BB2X1 g1339__7098(.A0N (n_77), .A1N (led[15]), .B0 (n_78), .B1
       (flick), .Y (n_82));
  NAND2XL g1340__6131(.A (n_206), .B (n_78), .Y (n_81));
  OR2X1 g1341__1881(.A (n_76), .B (led[0]), .Y (n_80));
  NAND2BXL g1342__5115(.AN (n_77), .B (led[15]), .Y (n_79));
  DFFRHQX1 \led_reg[1] (.RN (rst), .CK (clk), .D (led_next[1]), .Q
       (led[1]));
  DFFRHQX1 \led_reg[6] (.RN (rst), .CK (clk), .D (led_next[6]), .Q
       (led[6]));
  DFFRHQX1 \led_reg[11] (.RN (rst), .CK (clk), .D (led_next[11]), .Q
       (led[11]));
  TLATNX2 \state_reg[0] (.GN (rst), .D (1'b0), .Q (state[0]), .QN
       (UNCONNECTED));
  DFFRHQX1 \led_reg[0] (.RN (rst), .CK (clk), .D (led_next[0]), .Q
       (led[0]));
  TLATNX2 \state_reg[1] (.GN (rst), .D (1'b0), .Q (state[1]), .QN
       (UNCONNECTED0));
  TLATNX2 \state_reg[2] (.GN (rst), .D (1'b0), .Q (state[2]), .QN
       (UNCONNECTED1));
  NAND2BXL g1350__7482(.AN (led[5]), .B (led[4]), .Y (n_75));
  NOR2XL g1351__4733(.A (n_207), .B (n_205), .Y (n_78));
  OR2X1 g1352__6161(.A (n_207), .B (n_71), .Y (n_77));
  NAND2XL g1353__9315(.A (n_207), .B (n_72), .Y (n_76));
  INVX1 g1357(.A (n_86), .Y (n_74));
  INVX1 g1359(.A (n_206), .Y (n_72));
  INVX1 g1361(.A (n_205), .Y (n_71));
  TLATX1 \led_next_reg[13] (.G (n_70), .D (n_65), .Q (led_next[13]),
       .QN (UNCONNECTED2));
  TLATX1 \led_next_reg[2] (.G (n_70), .D (n_62), .Q (led_next[2]), .QN
       (UNCONNECTED3));
  TLATX1 \led_next_reg[11] (.G (n_70), .D (n_53), .Q (led_next[11]),
       .QN (UNCONNECTED4));
  TLATX1 \led_next_reg[12] (.G (n_70), .D (n_66), .Q (led_next[12]),
       .QN (UNCONNECTED5));
  TLATX1 \led_next_reg[1] (.G (n_70), .D (n_63), .Q (led_next[1]), .QN
       (UNCONNECTED6));
  TLATX1 \led_next_reg[14] (.G (n_70), .D (n_64), .Q (led_next[14]),
       .QN (UNCONNECTED7));
  TLATX1 \led_next_reg[3] (.G (n_70), .D (n_67), .Q (led_next[3]), .QN
       (UNCONNECTED8));
  TLATX1 \led_next_reg[4] (.G (n_70), .D (n_56), .Q (led_next[4]), .QN
       (UNCONNECTED9));
  TLATX1 \led_next_reg[9] (.G (n_70), .D (n_55), .Q (led_next[9]), .QN
       (UNCONNECTED10));
  TLATX1 \led_next_reg[6] (.G (n_70), .D (n_58), .Q (led_next[6]), .QN
       (UNCONNECTED11));
  TLATX1 \led_next_reg[7] (.G (n_70), .D (n_57), .Q (led_next[7]), .QN
       (UNCONNECTED12));
  TLATX1 \led_next_reg[8] (.G (n_70), .D (n_60), .Q (led_next[8]), .QN
       (UNCONNECTED13));
  TLATX1 \led_next_reg[5] (.G (n_70), .D (n_59), .Q (led_next[5]), .QN
       (UNCONNECTED14));
  TLATX1 \led_next_reg[10] (.G (n_70), .D (n_54), .Q (led_next[10]),
       .QN (UNCONNECTED15));
  TLATX1 \led_next_reg[15] (.G (n_70), .D (n_49), .Q (led_next[15]),
       .QN (UNCONNECTED16));
  TLATX1 \led_next_reg[0] (.G (n_70), .D (n_61), .Q (led_next[0]), .QN
       (UNCONNECTED17));
  OAI21X1 g2216__9945(.A0 (led[10]), .A1 (n_18), .B0 (n_69), .Y (n_70));
  AOI221X1 g2217__2883(.A0 (state[0]), .A1 (n_47), .B0 (state[1]), .B1
       (n_48), .C0 (n_68), .Y (n_69));
  NOR3XL g2218__2346(.A (state[0]), .B (state[1]), .C (n_43), .Y
       (n_68));
  OAI2BB1X1 g2219__1666(.A0N (led[4]), .A1N (n_34), .B0 (n_52), .Y
       (n_67));
  OAI2BB1X1 g2220__7410(.A0N (led[13]), .A1N (n_33), .B0 (n_44), .Y
       (n_66));
  OAI2BB1X1 g2221__6417(.A0N (led[14]), .A1N (n_32), .B0 (n_51), .Y
       (n_65));
  OAI2BB1X1 g2222__5477(.A0N (led[15]), .A1N (n_30), .B0 (n_50), .Y
       (n_64));
  OAI2BB1X1 g2223__2398(.A0N (led[2]), .A1N (n_28), .B0 (n_46), .Y
       (n_63));
  OAI2BB1X1 g2224__5107(.A0N (led[3]), .A1N (n_27), .B0 (n_45), .Y
       (n_62));
  OAI2BB1X1 g2225__6260(.A0N (led[1]), .A1N (n_29), .B0 (n_31), .Y
       (n_61));
  OAI2BB1X1 g2226__4319(.A0N (led[9]), .A1N (n_21), .B0 (n_39), .Y
       (n_60));
  OAI2BB1X1 g2227__8428(.A0N (led[6]), .A1N (n_24), .B0 (n_42), .Y
       (n_59));
  OAI2BB1X1 g2228__5526(.A0N (led[7]), .A1N (n_23), .B0 (n_41), .Y
       (n_58));
  OAI2BB1X1 g2229__6783(.A0N (led[8]), .A1N (n_22), .B0 (n_40), .Y
       (n_57));
  OAI2BB1X1 g2230__3680(.A0N (led[5]), .A1N (n_25), .B0 (n_35), .Y
       (n_56));
  OAI2BB1X1 g2231__1617(.A0N (led[10]), .A1N (n_20), .B0 (n_38), .Y
       (n_55));
  OAI2BB1X1 g2232__2802(.A0N (led[11]), .A1N (n_19), .B0 (n_37), .Y
       (n_54));
  OAI2BB1X1 g2233__1705(.A0N (led[12]), .A1N (n_26), .B0 (n_36), .Y
       (n_53));
  NAND3XL g2234__5122(.A (state[0]), .B (led[2]), .C (n_10), .Y (n_52));
  NAND3XL g2235__8246(.A (state[0]), .B (led[12]), .C (n_4), .Y (n_51));
  NAND3XL g2236__7098(.A (state[0]), .B (led[13]), .C (n_14), .Y
       (n_50));
  AND3XL g2237__6131(.A (led[14]), .B (state[0]), .C (n_15), .Y (n_49));
  NOR2XL g2238__1881(.A (state[0]), .B (n_17), .Y (n_48));
  NOR2BX1 g2239__5115(.AN (n_16), .B (state[1]), .Y (n_47));
  NAND3XL g2240__7482(.A (state[0]), .B (led[0]), .C (n_12), .Y (n_46));
  NAND3XL g2241__4733(.A (state[0]), .B (led[1]), .C (n_11), .Y (n_45));
  NAND3XL g2242__6161(.A (state[0]), .B (led[11]), .C (n_0), .Y (n_44));
  AOI31X1 g2243__9315(.A0 (led[0]), .A1 (state[2]), .A2 (n_210), .B0
       (n_1), .Y (n_43));
  NAND3XL g2244__9945(.A (state[0]), .B (led[4]), .C (n_8), .Y (n_42));
  NAND3XL g2245__2883(.A (state[0]), .B (led[5]), .C (n_7), .Y (n_41));
  NAND3XL g2246__2346(.A (state[0]), .B (led[6]), .C (n_6), .Y (n_40));
  NAND3XL g2247__1666(.A (state[0]), .B (led[7]), .C (n_5), .Y (n_39));
  NAND3XL g2248__7410(.A (state[0]), .B (led[8]), .C (n_3), .Y (n_38));
  NAND3XL g2249__6417(.A (state[0]), .B (led[9]), .C (n_2), .Y (n_37));
  NAND3XL g2250__5477(.A (state[0]), .B (led[10]), .C (n_13), .Y
       (n_36));
  NAND3XL g2251__2398(.A (state[0]), .B (led[3]), .C (n_9), .Y (n_35));
  AOI2BB1X1 g2252__5107(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_34));
  AOI2BB1X1 g2253__6260(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_33));
  AOI2BB1X1 g2254__4319(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_32));
  OAI2BB1X1 g2255__8428(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_31));
  AOI2BB1X1 g2256__5526(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_30));
  AOI2BB1X1 g2257__6783(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_29));
  AOI2BB1X1 g2258__3680(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_28));
  AOI2BB1X1 g2259__1617(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_27));
  AOI2BB1X1 g2260__2802(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_26));
  AOI2BB1X1 g2261__1705(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_25));
  AOI2BB1X1 g2262__5122(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_24));
  AOI2BB1X1 g2263__8246(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_23));
  AOI2BB1X1 g2264__7098(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_22));
  AOI2BB1X1 g2265__6131(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_21));
  AOI2BB1X1 g2266__1881(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_20));
  AOI2BB1X1 g2267__5115(.A0N (state[1]), .A1N (state[2]), .B0
       (state[0]), .Y (n_19));
  NAND3BXL g2268__7482(.AN (state[2]), .B (state[1]), .C (state[0]), .Y
       (n_18));
  AOI22XL g2269__4733(.A0 (led[5]), .A1 (n_93), .B0 (led[0]), .B1
       (state[2]), .Y (n_17));
  OAI22XL g2270__6161(.A0 (led[15]), .A1 (state[2]), .B0 (led[5]), .B1
       (n_92), .Y (n_16));
  NAND2XL g2271__9315(.A (state[2]), .B (state[1]), .Y (n_15));
  NAND2XL g2272__9945(.A (state[2]), .B (state[1]), .Y (n_14));
  DFFRHQX1 \led_reg[13] (.RN (rst), .CK (clk), .D (led_next[13]), .Q
       (led[13]));
  DFFRHQX1 \led_reg[4] (.RN (rst), .CK (clk), .D (led_next[4]), .Q
       (led[4]));
  DFFRHQX1 \led_reg[12] (.RN (rst), .CK (clk), .D (led_next[12]), .Q
       (led[12]));
  DFFRHQX1 \led_reg[8] (.RN (rst), .CK (clk), .D (led_next[8]), .Q
       (led[8]));
  DFFRHQX1 \led_reg[9] (.RN (rst), .CK (clk), .D (led_next[9]), .Q
       (led[9]));
  DFFRHQX1 \led_reg[14] (.RN (rst), .CK (clk), .D (led_next[14]), .Q
       (led[14]));
  DFFRHQX1 \led_reg[3] (.RN (rst), .CK (clk), .D (led_next[3]), .Q
       (led[3]));
  DFFRHQX1 \led_reg[15] (.RN (rst), .CK (clk), .D (led_next[15]), .Q
       (led[15]));
  DFFRHQX1 \led_reg[7] (.RN (rst), .CK (clk), .D (led_next[7]), .Q
       (led[7]));
  DFFRHQX1 \led_reg[2] (.RN (rst), .CK (clk), .D (led_next[2]), .Q
       (led[2]));
  DFFRHQX1 \led_reg[10] (.RN (rst), .CK (clk), .D (led_next[10]), .Q
       (led[10]));
  DFFRHQX1 \led_reg[5] (.RN (rst), .CK (clk), .D (led_next[5]), .Q
       (led[5]));
  NAND2XL g2285__2883(.A (state[2]), .B (state[1]), .Y (n_13));
  NAND2XL g2286__2346(.A (state[2]), .B (state[1]), .Y (n_12));
  NAND2XL g2287__1666(.A (state[2]), .B (state[1]), .Y (n_11));
  NAND2XL g2288__7410(.A (state[2]), .B (state[1]), .Y (n_10));
  NAND2XL g2289__6417(.A (state[2]), .B (state[1]), .Y (n_9));
  NAND2XL g2290__5477(.A (state[2]), .B (state[1]), .Y (n_8));
  NAND2XL g2291__2398(.A (state[2]), .B (state[1]), .Y (n_7));
  NAND2XL g2292__5107(.A (state[2]), .B (state[1]), .Y (n_6));
  NAND2XL g2293__6260(.A (state[2]), .B (state[1]), .Y (n_5));
  NAND2XL g2294__4319(.A (state[2]), .B (state[1]), .Y (n_4));
  NAND2XL g2295__8428(.A (state[2]), .B (state[1]), .Y (n_3));
  NAND2XL g2296__5526(.A (state[2]), .B (state[1]), .Y (n_2));
  NOR2XL g2297__6783(.A (state[2]), .B (flick), .Y (n_1));
  NAND2XL g2298__3680(.A (state[2]), .B (state[1]), .Y (n_0));
endmodule

